/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useState } from "react";
import * as XLSX from "xlsx";
import { restoreDatabaseFromExcel } from "@/app/actions/admin/restoreActions";
import { useBackNavigation } from "@/hooks/useBackNavigation";
import NavigationLoader from "@/components/ui/NavigationLoader";
import { 
  ArrowLeft, UploadCloud, CheckCircle2, 
  Loader2, AlertTriangle, DatabaseBackup, XCircle
} from "lucide-react";

export default function RestoreDataPage() {
  const { isNavigating, handleBack } = useBackNavigation("/admin/advanced-tools");
  
  const [loading, setLoading] = useState(false);
  const [fileData, setFileData] = useState<any[] | null>(null);
  const [fileName, setFileName] = useState("");
  const [result, setResult] = useState<any>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    const reader = new FileReader();

    reader.onload = (evt) => {
      try {
        const arrayBuffer = evt.target?.result;
        if (!arrayBuffer) return;

        const wb = XLSX.read(arrayBuffer, { type: "array" });
        const ws = wb.Sheets[wb.SheetNames[0]];
        const rawData = XLSX.utils.sheet_to_json(ws);
        
        setFileData(rawData);
      } catch (err) {
        alert("Error reading backup file format.");
      }
    };

    reader.readAsArrayBuffer(file);
  };

  const handleRestore = async () => {
    if (!fileData) return;
    setLoading(true);
    
    const res = await restoreDatabaseFromExcel(fileData);
    setResult(res);
    setFileData(null);
    setLoading(false);
  };

  if (isNavigating) return <NavigationLoader message="Routing..." />;

  return (
    <main className="min-h-screen flex flex-col items-center w-full max-w-md mx-auto shadow-2xl bg-gray-50 dark:bg-gray-950 relative">
      <div className="w-full h-full p-4 pt-6 pb-32">
        
        {/* Header */}
        <div className="flex items-center gap-3 mb-6 bg-white dark:bg-gray-900 p-3 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm">
          <button onClick={() => handleBack()} className="p-2 bg-gray-100 dark:bg-gray-800 rounded-xl active:scale-90 transition">
            <ArrowLeft className="w-5 h-5 text-gray-700 dark:text-gray-300" />
          </button>
          <div>
            <h1 className="text-lg font-black text-amber-600 flex items-center gap-2">
              <DatabaseBackup className="w-4 h-4" /> Restore Backup
            </h1>
            <p className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">System Recovery</p>
          </div>
        </div>

        {!result ? (
          <div className="space-y-6">
            
            <div className="bg-amber-50 dark:bg-amber-900/10 p-4 rounded-2xl border border-amber-100 dark:border-amber-900/30 flex gap-3">
              <AlertTriangle className="w-6 h-6 text-amber-600 shrink-0" />
              <div>
                <p className="text-xs font-bold text-amber-800 dark:text-amber-400 uppercase tracking-widest">Warning</p>
                <p className="text-[10px] text-amber-700/80 dark:text-amber-400/80 mt-1 leading-relaxed font-bold">
                  Upload an exact `.xlsx` file generated by the <strong className="font-black text-amber-600">Database Export</strong> tool. If a record already exists, this tool will OVERWRITE it with the data in the Excel file.
                </p>
              </div>
            </div>

            {!fileData ? (
              <div className="bg-white dark:bg-gray-900 border-2 border-dashed border-gray-200 dark:border-gray-800 rounded-[2.5rem] p-10 text-center transition-all hover:border-amber-500 shadow-sm">
                <input 
                  type="file" 
                  id="backup-upload" 
                  className="hidden" 
                  accept=".xlsx, .xls" 
                  onChange={handleFileUpload}
                />
                <label htmlFor="backup-upload" className="cursor-pointer group block">
                  <div className="bg-amber-50 dark:bg-amber-900/20 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 group-hover:scale-110 transition-transform">
                    <UploadCloud className="w-8 h-8 text-amber-500" />
                  </div>
                  <p className="text-lg font-black text-gray-900 dark:text-white">Select Backup File</p>
                  <p className="text-[10px] text-gray-400 mt-2 uppercase tracking-widest font-bold">.xlsx format only</p>
                </label>
              </div>
            ) : (
              <div className="bg-white dark:bg-gray-900 p-6 rounded-[2rem] border border-amber-200 dark:border-amber-900/30 shadow-lg text-center animate-in zoom-in-95">
                <DatabaseBackup className="w-16 h-16 text-amber-500 mx-auto mb-4" />
                <h3 className="font-black text-lg text-gray-900 dark:text-white truncate px-4">{fileName}</h3>
                <p className="text-xs text-amber-600 font-bold mt-1 bg-amber-50 dark:bg-amber-900/20 py-1 px-3 rounded-full inline-block">
                  {fileData.length} Records Found
                </p>

                <div className="grid grid-cols-2 gap-3 mt-8">
                  <button 
                    onClick={() => setFileData(null)} 
                    disabled={loading}
                    className="py-4 bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300 font-bold rounded-xl active:scale-95 transition-transform"
                  >
                    Cancel
                  </button>
                  <button 
                    onClick={handleRestore}
                    disabled={loading}
                    className="py-4 bg-amber-600 text-white font-black rounded-xl shadow-lg shadow-amber-200 dark:shadow-none active:scale-95 transition-transform flex justify-center items-center gap-2"
                  >
                    {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : "START RESTORE"}
                  </button>
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="bg-white dark:bg-gray-900 rounded-[2.5rem] p-8 border shadow-xl animate-in zoom-in-95">
             <div className="flex flex-col items-center text-center mb-8">
               <div className="p-4 bg-green-100 dark:bg-green-900/30 rounded-full mb-4">
                 <CheckCircle2 className="w-12 h-12 text-green-600 dark:text-green-400" />
               </div>
               <h2 className="text-2xl font-black text-gray-900 dark:text-white">Restore Complete</h2>
               <p className="text-xs text-gray-500 font-medium mt-1">Database has been synchronized with the backup file.</p>
             </div>

             <div className="grid grid-cols-2 gap-4 mb-6">
               <div className="bg-green-50 dark:bg-green-900/20 p-4 rounded-2xl border border-green-100 dark:border-green-900/30 text-center">
                  <p className="text-[10px] font-black text-green-600 uppercase tracking-widest mb-1">Restored</p>
                  <p className="text-3xl font-black text-gray-900 dark:text-white">{result.successCount}</p>
               </div>
               <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-2xl border border-red-100 dark:border-red-900/30 text-center">
                  <p className="text-[10px] font-black text-red-600 uppercase tracking-widest mb-1">Failed</p>
                  <p className="text-3xl font-black text-gray-900 dark:text-white">{result.errorCount}</p>
               </div>
             </div>

             {result.errors?.length > 0 && (
               <div className="mb-6 p-3 bg-red-50 dark:bg-red-900/10 rounded-xl border border-red-100 dark:border-red-900/30 max-h-32 overflow-y-auto">
                  <div className="flex items-center gap-2 mb-2 text-red-600"><XCircle className="w-3 h-3" /><span className="text-[10px] font-black uppercase">Error Logs</span></div>
                  {result.errors.map((err: string, i: number) => (
                    <p key={i} className="text-[9px] text-red-500 font-medium border-b border-red-100 dark:border-red-900/50 py-1 last:border-0">{err}</p>
                  ))}
               </div>
             )}

             <button 
               onClick={() => setResult(null)}
               className="w-full py-4 bg-gray-900 dark:bg-white text-white dark:text-gray-900 font-black rounded-xl active:scale-95 transition-transform"
             >
               DONE
             </button>
          </div>
        )}
      </div>
    </main>
  );
}